# RE start:
$ ID : (a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|A|B|C|D|E|F|G|H|I|J|K|L|M|N|O|P|Q|R|S|T|U|V|W|X|Y|Z)*
$ INTEGER : (1|2|3|4|5|6|7|8|9)*
$ OPERATOR : +|-|=|\*|\/|\(|\)|{|}
$ DELIMITER : ;|,|.|~|!|@|"|'
# RE end
#~代表空格, !代表tab, @代表换行

# keywords:
% abstract, assert, boolean, break, byte, case, catch, char, class, const, continue, default, do, double, else, enum, extends, false, final, finally,float, for, goto, if, implements, import, instanceof, int, interface, long, native, new, null, out, print, println, package, private, protected, public, return, System, short, static, strictfp, super, switch, synchronized, this, throw, throws, transient, try, true, void, volatile, while